spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kar_outdoor?currentSchema=karoutdoordb
    username: kardbuser
    password: Eymen@1907
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

server:
  port: 8088